### ISSUE TITLE
Can't configure TV Glitch vertical speed

### ISSUE THREAD

**Issue by gabrielstuff** [brianchirls/Seriously.js#82]
Hi,

I'm playing with the tv glitch option, and I try to make the vertical band go slower.

Curently to animate the glitch I'm using : 

```
var draw = function() {
      tv.time = Date.now();
      target.render();
      requestAnimationFrame(draw);
  }

  draw();
```

tv is the effect. the parameters are : 

```
  tv.distortion = 0.01;
  tv.verticalSync = 0;
  tv.scanlines = 0.22;
  tv.lineSync = 0.01;
  tv.frameSharpness = 10.67;
  tv.frameLimit = 0.3644;
  tv.bars = 0.25;
```

Any more information would be great !

Thanks

**Comment by brianchirls** [comment]
Hi @gabrielstuff,

Currently, the best/only way to adjust the speed of the vertical bands is to adjust the value you pass to the `time` parameter. That value is best represented in seconds, not milliseconds, because it was intended to synchronize with a video element, which also reports its time in seconds.

```Javascript
   tv.time = Date.now() / 1000;
```
You can divide by a different number to get the bars moving slower or faster.

I will look into making sure this is standard across all the effects and reflected in any examples or demos for the next version. And I'll consider adding a time scaling parameter to the effect.  Would that be helpful?

I'll keep this issue open until then.

**Comment by gabrielstuff** [comment]
Hi !

It does the trick indeed ! Thanks a lot. Playing with parameters it appears that the real issue is the distortion speed : 

`tv.distortion = 0.02`

This parameter only play on the amount not the speed, see the horizontal line is going slowly down but the distortion keep on the speed.

![speedy](https://cloud.githubusercontent.com/assets/285033/6202782/e465ecb8-b4fc-11e4-90d0-77f8996c6c14.gif)

Thanks anyway. Should I open an other issue and close this one ?

G

**Comment by brianchirls** [comment]
How's that?

And I'm gonna open another issue for generally improving all time parameters on effect plugins.
